<?php

namespace Database\Seeders;

use App\Models\Hotel\Accommodation;
use Illuminate\Database\Seeder;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $accommodation = [
            [
                'hotel_id' => 1,
                'room_type' => 'Standard Double City View',
                'occupancy' => '2',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'City View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ],
            [
                'hotel_id' => 1,
                'room_type' => 'Standard Double Sea View',
                'occupancy' => '2',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'City View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ],
            [
                'hotel_id' => 1,
                'room_type' => 'Superior Twin Sea View',
                'occupancy' => '3',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'Sea View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ],

            [
                'hotel_id' => 2,
                'room_type' => 'Standard Double City View',
                'occupancy' => '2',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'City View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ],
            [
                'hotel_id' => 2,
                'room_type' => 'Standard Double Sea View',
                'occupancy' => '2',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'City View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ],
            [
                'hotel_id' => 2,
                'room_type' => 'Superior Twin Sea View',
                'occupancy' => '3',
                'number_of_rooms' => '1',
                'room_size' => '27 m²',
                'room_view' => 'Sea View',
                'beds' => '1',
                'bathrooms' => '1',
                'features' => [
                    'Linens',
                    'Tea/Coffee maker',
                    'Air conditioning',
                    'Safe',
                    'Ironing facilities',
                    'Fan',
                    'Refrigerator',
                    'Electric kettle',
                    'Desk',
                    'TV',
                    'Telephone',
                    'Flat-screen TV',
                    'Cable channels',
                    'Wake-up service',
                    'Single-room AC for guest accommodation',
                ],
                'sort_order' => 0,
                'status' => 1,
            ]
        ];

        foreach ($accommodation as $key => $value) {
            (new Accommodation())->newQuery()->create($value);
        }
    }
}
